In [1]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\ap036\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4687, 1552, 2872, 9822],
 [4687, 1552, 2872, 6856],
 [4687, 958, 2872, 9609],
 [967, 263, 3413, 4407, 6731],
 [967, 263, 3413, 4407, 927],
 [8353, 4687, 2115, 2872, 8949],
 [1350, 9112, 6705, 4407]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4687 1552 2872 9822]
 [   0    0    0    0 4687 1552 2872 6856]
 [   0    0    0    0 4687  958 2872 9609]
 [   0    0    0  967  263 3413 4407 6731]
 [   0    0    0  967  263 3413 4407  927]
 [   0    0    0 8353 4687 2115 2872 8949]
 [   0    0    0    0 1350 9112 6705 4407]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 199ms/step


array([[[-0.03429885, -0.00146253,  0.02350272, -0.03734847,
         -0.03414913,  0.03160561,  0.03244246,  0.02691627,
          0.00262732,  0.01829332],
        [-0.03429885, -0.00146253,  0.02350272, -0.03734847,
         -0.03414913,  0.03160561,  0.03244246,  0.02691627,
          0.00262732,  0.01829332],
        [-0.03429885, -0.00146253,  0.02350272, -0.03734847,
         -0.03414913,  0.03160561,  0.03244246,  0.02691627,
          0.00262732,  0.01829332],
        [-0.03429885, -0.00146253,  0.02350272, -0.03734847,
         -0.03414913,  0.03160561,  0.03244246,  0.02691627,
          0.00262732,  0.01829332],
        [-0.01526538, -0.01584234,  0.03214142,  0.02882215,
         -0.03766847,  0.04643795,  0.00940449, -0.04327573,
         -0.04995315,  0.00123532],
        [ 0.02150818,  0.03207934, -0.00683891,  0.03755257,
          0.02661884, -0.047797  , -0.01759323,  0.01116528,
          0.02209623, -0.03007394],
        [ 0.02854775, -0.00706669, -0.03590447,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4687, 1552, 2872, 9822])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 69ms/step


array([[-0.03429885, -0.00146253,  0.02350272, -0.03734847, -0.03414913,
         0.03160561,  0.03244246,  0.02691627,  0.00262732,  0.01829332],
       [-0.03429885, -0.00146253,  0.02350272, -0.03734847, -0.03414913,
         0.03160561,  0.03244246,  0.02691627,  0.00262732,  0.01829332],
       [-0.03429885, -0.00146253,  0.02350272, -0.03734847, -0.03414913,
         0.03160561,  0.03244246,  0.02691627,  0.00262732,  0.01829332],
       [-0.03429885, -0.00146253,  0.02350272, -0.03734847, -0.03414913,
         0.03160561,  0.03244246,  0.02691627,  0.00262732,  0.01829332],
       [-0.01526538, -0.01584234,  0.03214142,  0.02882215, -0.03766847,
         0.04643795,  0.00940449, -0.04327573, -0.04995315,  0.00123532],
       [ 0.02150818,  0.03207934, -0.00683891,  0.03755257,  0.02661884,
        -0.047797  , -0.01759323,  0.01116528,  0.02209623, -0.03007394],
       [ 0.02854775, -0.00706669, -0.03590447,  0.04628202,  0.00434121,
         0.01688034, -0.04799834,  0.01797869